name: Secure Integration Tests

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  secure-integration-tests:
    name: Secure Integration Test - ES ${{ matrix.elastic_stack_version }} ${{ matrix.snapshot && '(Snapshot)' || '' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elastic_stack_version:
          - "7.current"
          - "8.current"
          - "9.current"
        snapshot: [false, true]
        include:
          - elastic_stack_version: "main"
            snapshot: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup test environment
        id: setup
        uses: ./.github/actions/setup
        with:
          elastic_stack_version: ${{ matrix.elastic_stack_version }}
          snapshot: ${{ matrix.snapshot }}
          secure_integration: true

      - name: Run secure integration tests
        if: steps.setup.outputs.skip != 'true'
        run: |
          bash .ci/docker-run.sh

      # NOTE: no cleanup needed when running on ephemeral runners
