name: Unit Tests

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  tests:
    uses: logstash-plugins/.ci/.github/workflows/test.yml@feature/github-actions
    permissions:
      contents: read
