name: Unit Tests

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

## Concurrency only allowed in the main branch.
## So old builds running for old commits within the same Pull Request are cancelled
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:
  test:
    name: Test - ES ${{ matrix.elastic-stack-version }}${{ matrix.snapshot && ' (Snapshot)' || '' }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        elastic-stack-version:
          - '8.current'
          - '9.previous'
          - '9.current'
          - 'main'
        snapshot: [false, true]
        docker-env: ['dockerjdk21.env']
        exclude:
          # main only runs as snapshot
          - elastic-stack-version: 'main'
            snapshot: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup test environment
        id: setup
        uses: logstash-plugins/.ci/setup@feature/github-actions
        with:
          elastic-stack-version: ${{ matrix.elastic-stack-version }}
          snapshot: ${{ matrix.snapshot }}
          docker-env: ${{ matrix.docker-env }}

      - name: Run tests
        if: steps.setup.outputs.skip != 'true'
        timeout-minutes: 60
        run: bash .ci/docker-run.sh
