name: Unit Tests

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  tests:
    uses: logstash-plugins/.ci/.github/workflows/test.yml@feature/github-actions
    permissions:
      contents: read
